CREATE TABLE Users (id SERIAL PRIMARY KEY, username VARCHAR(255) UNIQUE NOT NULL, email VARCHAR(255) UNIQUE NOT NULL, password_hash VARCHAR(255) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE Roles (id SERIAL PRIMARY KEY, name VARCHAR(255) UNIQUE NOT NULL, description TEXT);
CREATE TABLE Applications (id SERIAL PRIMARY KEY, user_id INTEGER REFERENCES Users(id) ON DELETE CASCADE, name VARCHAR(255) NOT NULL, description TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE Components (id SERIAL PRIMARY KEY, application_id INTEGER REFERENCES Applications(id) ON DELETE CASCADE, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, config JSONB);
CREATE TABLE Templates (id SERIAL PRIMARY KEY, name VARCHAR(255) UNIQUE NOT NULL, structure JSONB);
CREATE TABLE Workflows (id SERIAL PRIMARY KEY, application_id INTEGER REFERENCES Applications(id) ON DELETE CASCADE, name VARCHAR(255) NOT NULL, trigger_event VARCHAR(255), actions JSONB);
CREATE TABLE Logs (id SERIAL PRIMARY KEY, application_id INTEGER REFERENCES Applications(id) ON DELETE CASCADE, message TEXT, level VARCHAR(50), timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP);