apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: enterprise-app
  template:
    metadata:
      labels:
        app: enterprise-app
    spec:
      containers:
      - name: frontend
        image: enterprise-app-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: production
      - name: backend
        image: enterprise-app-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: uri
---
apiVersion: v1
kind: Service
metadata:
  name: enterprise-app
spec:
  selector:
    app: enterprise-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer