export default function Page() {
  return (
    <main className="min-h-screen bg-gray-50">
      <section className="bg-gradient-to-br from-blue-600 to-indigo-700 text-white py-16">
        <div className="max-w-6xl mx-auto px-6">
          <h1 className="text-4xl md:text-5xl font-extrabold mb-4">Budibase | Build internal tools in minutes, the easy way</h1>
          <p className="text-lg md:text-xl text-blue-100 max-w-2xl">
            Enterprise-grade application generated by AI with modern UX and security.
          </p>
          <div className="mt-8 flex gap-3">
            <a href="/" className="inline-flex items-center px-5 py-3 rounded-md bg-white text-blue-700 font-medium shadow hover:shadow-md">Get Started</a>
            <a href="/marketplace" className="inline-flex items-center px-5 py-3 rounded-md border border-white/30 text-white hover:bg-white/10">View Marketplace</a>
          </div>
        </div>
      </section>
      <section className="py-14">
        <div className="max-w-6xl mx-auto px-6">
          <h2 className="text-2xl font-semibold mb-6 text-gray-900">Key Features</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            <div className="p-5 bg-white rounded-lg shadow-sm border"><div className="font-medium text-gray-900 mb-1">Drag-and-drop interface for building applications</div><p className="text-gray-600 text-sm">Built-in best practices, scalable architecture, and secure defaults.</p></div>
            <div className="p-5 bg-white rounded-lg shadow-sm border"><div className="font-medium text-gray-900 mb-1">Pre-built templates for common Budibase | Build internal tools in minutes, the easy ways</div><p className="text-gray-600 text-sm">Built-in best practices, scalable architecture, and secure defaults.</p></div>
            <div className="p-5 bg-white rounded-lg shadow-sm border"><div className="font-medium text-gray-900 mb-1">Integration with popular databases and APIs</div><p className="text-gray-600 text-sm">Built-in best practices, scalable architecture, and secure defaults.</p></div>
            <div className="p-5 bg-white rounded-lg shadow-sm border"><div className="font-medium text-gray-900 mb-1">User authentication and role-based access control</div><p className="text-gray-600 text-sm">Built-in best practices, scalable architecture, and secure defaults.</p></div>
            <div className="p-5 bg-white rounded-lg shadow-sm border"><div className="font-medium text-gray-900 mb-1">Real-time collaboration and version control</div><p className="text-gray-600 text-sm">Built-in best practices, scalable architecture, and secure defaults.</p></div>
            <div className="p-5 bg-white rounded-lg shadow-sm border"><div className="font-medium text-gray-900 mb-1">Customizable UI components</div><p className="text-gray-600 text-sm">Built-in best practices, scalable architecture, and secure defaults.</p></div>
          </div>
        </div>
      </section>
    </main>
  );
}
