name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 123456789012.dkr.ecr.us-east-1.amazonaws.com

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
    - name: Build Docker image
      run: |
        docker build -t $ECR_REGISTRY/enterprise-app-frontend:latest ./frontend
        docker build -t $ECR_REGISTRY/enterprise-app-backend:latest ./backend
    - name: Push to ECR
      run: |
        docker push $ECR_REGISTRY/enterprise-app-frontend:latest
        docker push $ECR_REGISTRY/enterprise-app-backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to Kubernetes
      uses: azure/k8s-deploy@v1
      with:
        manifests: k8s/deployment.yaml

  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run security scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: $ECR_REGISTRY/enterprise-app-frontend:latest